"""Alembic migration environment.

Wires Alembic to the platform's ORM metadata so migrations can be autogenerated
and applied. Key choices:

  * ``render_as_batch=True`` — SQLite cannot ALTER most things in place; batch
    mode recreates tables transparently so migrations are portable.
  * ``compare_type=True`` — detect column type changes during autogenerate.
  * ``DATABASE_URL`` (env var) overrides the ini URL, so the same migrations run
    against research SQLite and production Postgres unchanged.
"""
from __future__ import annotations

import os
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

# --- make the src-layout package importable --------------------------------
# env.py lives at src/momentum/persistence/migrations/env.py -> parents[3] == src
SRC = Path(__file__).resolve().parents[3]
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

# Importing the models package registers every table on Base.metadata.
from momentum.persistence.models import Base  # noqa: E402

config = context.config

# Environment variable wins over the ini file URL.
_db_url = os.environ.get("DATABASE_URL")
if _db_url:
    config.set_main_option("sqlalchemy.url", _db_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live DB connection."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations against a live connection."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
            compare_type=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
