"""initial schema

Creates the seven core tables of the Momentum Research Platform:
market_regimes, signals, position_sizes, trades, portfolio_snapshots,
risk_metrics and optimization_results. Every table carries an integer
primary key plus created_at / updated_at audit timestamps, with indexes,
unique constraints and foreign keys as defined by the ORM models.

Index creation uses batch_alter_table so the migration is SQLite-safe.

Revision ID: 0001
Revises:
Create Date: 2026-06-18
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_regimes',
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('benchmark_symbol', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('regime', sa.String(length=16), nullable=False),
    sa.Column('trend_state', sa.String(length=16), nullable=False),
    sa.Column('volatility_state', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('benchmark_close', sa.Float(), nullable=True),
    sa.Column('ma_fast', sa.Float(), nullable=True),
    sa.Column('ma_slow', sa.Float(), nullable=True),
    sa.Column('adx', sa.Float(), nullable=True),
    sa.Column('realized_vol', sa.Float(), nullable=True),
    sa.Column('breadth', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_regimes')),
    sa.UniqueConstraint('as_of', 'benchmark_symbol', 'model_version', name='uq_regime_asof_benchmark_model')
    )
    with op.batch_alter_table('market_regimes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_regimes_as_of'), ['as_of'], unique=False)
        batch_op.create_index('ix_market_regimes_asof_regime', ['as_of', 'regime'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_regimes_benchmark_symbol'), ['benchmark_symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_regimes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_regimes_regime'), ['regime'], unique=False)

    op.create_table('optimization_results',
    sa.Column('study_name', sa.String(length=64), nullable=False),
    sa.Column('optimizer', sa.String(length=24), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('param_hash', sa.String(length=64), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('objective', sa.String(length=32), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('sample', sa.String(length=16), nullable=False),
    sa.Column('fold', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.Date(), nullable=True),
    sa.Column('window_end', sa.Date(), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('sortino', sa.Float(), nullable=True),
    sa.Column('calmar', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('volatility_annual', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('expectancy_r', sa.Float(), nullable=True),
    sa.Column('num_trades', sa.Integer(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_results')),
    sa.UniqueConstraint('study_name', 'param_hash', 'sample', 'fold', name='uq_optresult_study_param_sample_fold')
    )
    with op.batch_alter_table('optimization_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimization_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_results_is_selected'), ['is_selected'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_results_objective_value'), ['objective_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_results_param_hash'), ['param_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_results_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_results_study_name'), ['study_name'], unique=False)
        batch_op.create_index('ix_optimization_results_study_objective', ['study_name', 'objective_value'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('positions_value', sa.Float(), nullable=False),
    sa.Column('num_positions', sa.Integer(), nullable=False),
    sa.Column('gross_exposure', sa.Float(), nullable=False),
    sa.Column('net_exposure', sa.Float(), nullable=False),
    sa.Column('long_exposure', sa.Float(), nullable=False),
    sa.Column('short_exposure', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('portfolio_heat', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('daily_pnl', sa.Float(), nullable=True),
    sa.Column('daily_return', sa.Float(), nullable=True),
    sa.Column('cumulative_return', sa.Float(), nullable=True),
    sa.Column('high_water_mark', sa.Float(), nullable=True),
    sa.Column('drawdown', sa.Float(), nullable=True),
    sa.Column('regime_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['regime_id'], ['market_regimes.id'], name=op.f('fk_portfolio_snapshots_regime_id_market_regimes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots')),
    sa.UniqueConstraint('run_id', 'session_date', name='uq_portfolio_snapshots_run_session')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_regime_id'), ['regime_id'], unique=False)
        batch_op.create_index('ix_portfolio_snapshots_run_asof', ['run_id', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_session_date'), ['session_date'], unique=False)

    op.create_table('signals',
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('strategy', sa.String(length=48), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('signal_type', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('breakout_level', sa.Float(), nullable=True),
    sa.Column('reference_price', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('regime_id', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['regime_id'], ['market_regimes.id'], name=op.f('fk_signals_regime_id_market_regimes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_regime_id'), ['regime_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_signals_run_symbol', ['run_id', 'symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_session_date'), ['session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_signal_type'), ['signal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_signals_symbol_ts', ['symbol', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_ts'), ['ts'], unique=False)

    op.create_table('position_sizes',
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=8), nullable=False),
    sa.Column('binding_constraint', sa.String(length=48), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('account_equity', sa.Float(), nullable=False),
    sa.Column('risk_per_trade_pct', sa.Float(), nullable=False),
    sa.Column('risk_dollars', sa.Float(), nullable=False),
    sa.Column('entry_reference', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('stop_distance', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('vol_estimate', sa.Float(), nullable=True),
    sa.Column('target_shares', sa.Integer(), nullable=True),
    sa.Column('approved_shares', sa.Integer(), nullable=True),
    sa.Column('target_notional', sa.Float(), nullable=True),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('portfolio_heat_before', sa.Float(), nullable=True),
    sa.Column('portfolio_heat_after', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_position_sizes_signal_id_signals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_sizes'))
    )
    with op.batch_alter_table('position_sizes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_sizes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_sizes_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_position_sizes_run_verdict', ['run_id', 'verdict'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_sizes_signal_id'), ['signal_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_position_sizes_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_sizes_verdict'), ['verdict'], unique=False)

    op.create_table('risk_metrics',
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('window', sa.String(length=24), nullable=False),
    sa.Column('portfolio_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('volatility_annual', sa.Float(), nullable=True),
    sa.Column('downside_deviation', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('sortino', sa.Float(), nullable=True),
    sa.Column('calmar', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('current_drawdown', sa.Float(), nullable=True),
    sa.Column('ulcer_index', sa.Float(), nullable=True),
    sa.Column('var_95', sa.Float(), nullable=True),
    sa.Column('cvar_95', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('correlation_benchmark', sa.Float(), nullable=True),
    sa.Column('gross_exposure', sa.Float(), nullable=True),
    sa.Column('portfolio_heat', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('expectancy_r', sa.Float(), nullable=True),
    sa.Column('avg_win_r', sa.Float(), nullable=True),
    sa.Column('avg_loss_r', sa.Float(), nullable=True),
    sa.Column('payoff_ratio', sa.Float(), nullable=True),
    sa.Column('num_trades', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_snapshot_id'], ['portfolio_snapshots.id'], name=op.f('fk_risk_metrics_portfolio_snapshot_id_portfolio_snapshots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_metrics')),
    sa.UniqueConstraint('run_id', 'scope', 'window', 'session_date', name='uq_risk_metrics_run_scope_window_date')
    )
    with op.batch_alter_table('risk_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_metrics_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_metrics_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_metrics_portfolio_snapshot_id'), ['portfolio_snapshot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_metrics_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_metrics_scope'), ['scope'], unique=False)
        batch_op.create_index('ix_risk_metrics_scope_date', ['scope', 'session_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_metrics_session_date'), ['session_date'], unique=False)

    op.create_table('trades',
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('entry_signal_id', sa.Integer(), nullable=True),
    sa.Column('position_size_id', sa.Integer(), nullable=True),
    sa.Column('regime_id', sa.Integer(), nullable=True),
    sa.Column('entry_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('initial_stop', sa.Float(), nullable=True),
    sa.Column('initial_risk', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('gross_pnl', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('mfe', sa.Float(), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('bars_held', sa.Integer(), nullable=True),
    sa.Column('exit_reason', sa.String(length=24), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entry_signal_id'], ['signals.id'], name=op.f('fk_trades_entry_signal_id_signals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_size_id'], ['position_sizes.id'], name=op.f('fk_trades_position_size_id_position_sizes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['regime_id'], ['market_regimes.id'], name=op.f('fk_trades_regime_id_market_regimes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_entry_signal_id'), ['entry_signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_entry_ts'), ['entry_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_exit_ts'), ['exit_ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_position_size_id'), ['position_size_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_regime_id'), ['regime_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_trades_run_status', ['run_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_trades_symbol_entry_ts', ['symbol', 'entry_ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('ix_trades_symbol_entry_ts')
        batch_op.drop_index(batch_op.f('ix_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_trades_status'))
        batch_op.drop_index('ix_trades_run_status')
        batch_op.drop_index(batch_op.f('ix_trades_run_id'))
        batch_op.drop_index(batch_op.f('ix_trades_regime_id'))
        batch_op.drop_index(batch_op.f('ix_trades_position_size_id'))
        batch_op.drop_index(batch_op.f('ix_trades_exit_ts'))
        batch_op.drop_index(batch_op.f('ix_trades_entry_ts'))
        batch_op.drop_index(batch_op.f('ix_trades_entry_signal_id'))
        batch_op.drop_index(batch_op.f('ix_trades_created_at'))

    op.drop_table('trades')
    with op.batch_alter_table('risk_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_metrics_session_date'))
        batch_op.drop_index('ix_risk_metrics_scope_date')
        batch_op.drop_index(batch_op.f('ix_risk_metrics_scope'))
        batch_op.drop_index(batch_op.f('ix_risk_metrics_run_id'))
        batch_op.drop_index(batch_op.f('ix_risk_metrics_portfolio_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_risk_metrics_created_at'))
        batch_op.drop_index(batch_op.f('ix_risk_metrics_as_of'))

    op.drop_table('risk_metrics')
    with op.batch_alter_table('position_sizes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_sizes_verdict'))
        batch_op.drop_index(batch_op.f('ix_position_sizes_symbol'))
        batch_op.drop_index(batch_op.f('ix_position_sizes_signal_id'))
        batch_op.drop_index('ix_position_sizes_run_verdict')
        batch_op.drop_index(batch_op.f('ix_position_sizes_run_id'))
        batch_op.drop_index(batch_op.f('ix_position_sizes_created_at'))

    op.drop_table('position_sizes')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_ts'))
        batch_op.drop_index('ix_signals_symbol_ts')
        batch_op.drop_index(batch_op.f('ix_signals_symbol'))
        batch_op.drop_index(batch_op.f('ix_signals_status'))
        batch_op.drop_index(batch_op.f('ix_signals_signal_type'))
        batch_op.drop_index(batch_op.f('ix_signals_session_date'))
        batch_op.drop_index('ix_signals_run_symbol')
        batch_op.drop_index(batch_op.f('ix_signals_run_id'))
        batch_op.drop_index(batch_op.f('ix_signals_regime_id'))
        batch_op.drop_index(batch_op.f('ix_signals_created_at'))

    op.drop_table('signals')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_session_date'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_run_id'))
        batch_op.drop_index('ix_portfolio_snapshots_run_asof')
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_regime_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_created_at'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_as_of'))

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('optimization_results', schema=None) as batch_op:
        batch_op.drop_index('ix_optimization_results_study_objective')
        batch_op.drop_index(batch_op.f('ix_optimization_results_study_name'))
        batch_op.drop_index(batch_op.f('ix_optimization_results_run_id'))
        batch_op.drop_index(batch_op.f('ix_optimization_results_param_hash'))
        batch_op.drop_index(batch_op.f('ix_optimization_results_objective_value'))
        batch_op.drop_index(batch_op.f('ix_optimization_results_is_selected'))
        batch_op.drop_index(batch_op.f('ix_optimization_results_created_at'))

    op.drop_table('optimization_results')
    with op.batch_alter_table('market_regimes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_regimes_regime'))
        batch_op.drop_index(batch_op.f('ix_market_regimes_created_at'))
        batch_op.drop_index(batch_op.f('ix_market_regimes_benchmark_symbol'))
        batch_op.drop_index('ix_market_regimes_asof_regime')
        batch_op.drop_index(batch_op.f('ix_market_regimes_as_of'))

    op.drop_table('market_regimes')
    # ### end Alembic commands ###
