"""conviction scores

Creates the ``conviction_scores`` table: per-setup 0-100 score and band, the
eight normalized component scores, the explainable JSON breakdown, and links to
the originating trade / signal. Indexes created via batch_alter_table (SQLite-safe).

Revision ID: 0006
Revises: 0005
Create Date: 2026-06-19
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conviction_scores',
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=8), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('config_hash', sa.String(length=32), nullable=True),
    sa.Column('regime_score', sa.Float(), nullable=True),
    sa.Column('sector_strength', sa.Float(), nullable=True),
    sa.Column('relative_volume', sa.Float(), nullable=True),
    sa.Column('distance_to_ath', sa.Float(), nullable=True),
    sa.Column('trend_strength', sa.Float(), nullable=True),
    sa.Column('breadth', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('historical_edge', sa.Float(), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_conviction_scores_signal_id_signals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_conviction_scores_trade_id_trades'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conviction_scores'))
    )
    with op.batch_alter_table('conviction_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conviction_scores_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_conviction_scores_band'), ['band'], unique=False)
        batch_op.create_index(batch_op.f('ix_conviction_scores_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_conviction_scores_run_band', ['run_id', 'band'], unique=False)
        batch_op.create_index(batch_op.f('ix_conviction_scores_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conviction_scores_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_conviction_scores_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conviction_scores_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_conviction_scores_symbol_as_of', ['symbol', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_conviction_scores_trade_id'), ['trade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conviction_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conviction_scores_trade_id'))
        batch_op.drop_index('ix_conviction_scores_symbol_as_of')
        batch_op.drop_index(batch_op.f('ix_conviction_scores_symbol'))
        batch_op.drop_index(batch_op.f('ix_conviction_scores_signal_id'))
        batch_op.drop_index(batch_op.f('ix_conviction_scores_score'))
        batch_op.drop_index(batch_op.f('ix_conviction_scores_run_id'))
        batch_op.drop_index('ix_conviction_scores_run_band')
        batch_op.drop_index(batch_op.f('ix_conviction_scores_created_at'))
        batch_op.drop_index(batch_op.f('ix_conviction_scores_band'))
        batch_op.drop_index(batch_op.f('ix_conviction_scores_as_of'))

    op.drop_table('conviction_scores')
    # ### end Alembic commands ###
