"""orchestration runs

Creates the ``runs`` table: one row per orchestration invocation (paper /
backtest / live) recording mode, session date, lifecycle status, config hash and
the equity/trade outcome. This is the orchestration layer's state anchor for
crash recovery. Indexes created via batch_alter_table (SQLite-safe).

Revision ID: 0008
Revises: 0007
Create Date: 2026-06-19
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config_hash", sa.String(length=32), nullable=True),
        sa.Column("equity_start", sa.Float(), nullable=True),
        sa.Column("equity_end", sa.Float(), nullable=True),
        sa.Column("num_opened", sa.Integer(), nullable=False),
        sa.Column("num_closed", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("run_id", name="uq_runs_run_id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_as_of"), ["as_of"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_mode"), ["mode"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_status"))
        batch_op.drop_index(batch_op.f("ix_runs_run_id"))
        batch_op.drop_index(batch_op.f("ix_runs_mode"))
        batch_op.drop_index(batch_op.f("ix_runs_created_at"))
        batch_op.drop_index(batch_op.f("ix_runs_as_of"))

    op.drop_table("runs")
    # ### end Alembic commands ###
