"""audit log

Creates the append-only ``audit_log`` table: one immutable, twice-timestamped row
per material action (signal/order/position/risk/strategy/backtest events) with a
JSON payload and run/symbol/entity links. Indexes via batch_alter_table
(SQLite-safe).

Revision ID: 0009
Revises: 0008
Create Date: 2026-06-19
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("symbol", sa.String(length=16), nullable=True),
        sa.Column("entity_type", sa.String(length=24), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_audit_log_event_ts", ["event_type", "ts"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_event_type"), ["event_type"], unique=False)
        batch_op.create_index("ix_audit_log_run_event", ["run_id", "event_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_symbol"), ["symbol"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_ts"), ["ts"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_ts"))
        batch_op.drop_index(batch_op.f("ix_audit_log_symbol"))
        batch_op.drop_index(batch_op.f("ix_audit_log_run_id"))
        batch_op.drop_index("ix_audit_log_run_event")
        batch_op.drop_index(batch_op.f("ix_audit_log_event_type"))
        batch_op.drop_index("ix_audit_log_event_ts")
        batch_op.drop_index(batch_op.f("ix_audit_log_created_at"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
