"""watchlist entries

Revision ID: 3773ef717fb9
Revises: 0009
Create Date: 2026-06-20 22:10:06.625968
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watchlist_entries",
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("config_hash", sa.String(length=32), nullable=True),
        sa.Column("horizon", sa.String(length=16), nullable=False),
        sa.Column("horizon_label", sa.String(length=32), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("conviction", sa.Float(), nullable=False),
        sa.Column("base_conviction", sa.Float(), nullable=False),
        sa.Column("band", sa.String(length=8), nullable=True),
        sa.Column("sector", sa.String(length=32), nullable=True),
        sa.Column("risk_rating", sa.String(length=16), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("expected_move_pct", sa.Float(), nullable=True),
        sa.Column("expected_risk_pct", sa.Float(), nullable=True),
        sa.Column("reward_risk", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_entries")),
    )
    with op.batch_alter_table("watchlist_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watchlist_entries_as_of"), ["as_of"], unique=False)
        batch_op.create_index(
            "ix_watchlist_entries_as_of_horizon", ["as_of", "horizon"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_watchlist_entries_conviction"), ["conviction"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_watchlist_entries_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_watchlist_entries_horizon"), ["horizon"], unique=False)
        batch_op.create_index(
            "ix_watchlist_entries_horizon_rank", ["horizon", "rank"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_watchlist_entries_rank"), ["rank"], unique=False)
        batch_op.create_index(batch_op.f("ix_watchlist_entries_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_watchlist_entries_sector"), ["sector"], unique=False)
        batch_op.create_index(batch_op.f("ix_watchlist_entries_symbol"), ["symbol"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("watchlist_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watchlist_entries_symbol"))
        batch_op.drop_index(batch_op.f("ix_watchlist_entries_sector"))
        batch_op.drop_index(batch_op.f("ix_watchlist_entries_run_id"))
        batch_op.drop_index(batch_op.f("ix_watchlist_entries_rank"))
        batch_op.drop_index("ix_watchlist_entries_horizon_rank")
        batch_op.drop_index(batch_op.f("ix_watchlist_entries_horizon"))
        batch_op.drop_index(batch_op.f("ix_watchlist_entries_created_at"))
        batch_op.drop_index(batch_op.f("ix_watchlist_entries_conviction"))
        batch_op.drop_index("ix_watchlist_entries_as_of_horizon")
        batch_op.drop_index(batch_op.f("ix_watchlist_entries_as_of"))

    op.drop_table("watchlist_entries")
    # ### end Alembic commands ###
