"""scan pivot levels

Revision ID: 99b2ccbd3449
Revises: 0010
Create Date: 2026-06-20 22:43:58.137460
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_results", schema=None) as batch_op:
        batch_op.add_column(sa.Column("support_level", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("resistance_level", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_results", schema=None) as batch_op:
        batch_op.drop_column("resistance_level")
        batch_op.drop_column("support_level")

    # ### end Alembic commands ###
