"""setup lifecycles

Revision ID: 8fcdb0c876ba
Revises: 0011
Create Date: 2026-06-20 22:58:52.341022
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "setup_lifecycles",
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("previous_state", sa.String(length=16), nullable=True),
        sa.Column("state_since", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=160), nullable=True),
        sa.Column("conviction", sa.Float(), nullable=True),
        sa.Column("sector", sa.String(length=32), nullable=True),
        sa.Column("history", sa.JSON(), nullable=True),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_setup_lifecycles")),
    )
    with op.batch_alter_table("setup_lifecycles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_setup_lifecycles_as_of"), ["as_of"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_setup_lifecycles_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_setup_lifecycles_run_id"), ["run_id"], unique=False)
        batch_op.create_index("ix_setup_lifecycles_run_state", ["run_id", "state"], unique=False)
        batch_op.create_index(batch_op.f("ix_setup_lifecycles_sector"), ["sector"], unique=False)
        batch_op.create_index(batch_op.f("ix_setup_lifecycles_state"), ["state"], unique=False)
        batch_op.create_index(batch_op.f("ix_setup_lifecycles_symbol"), ["symbol"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("setup_lifecycles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_setup_lifecycles_symbol"))
        batch_op.drop_index(batch_op.f("ix_setup_lifecycles_state"))
        batch_op.drop_index(batch_op.f("ix_setup_lifecycles_sector"))
        batch_op.drop_index("ix_setup_lifecycles_run_state")
        batch_op.drop_index(batch_op.f("ix_setup_lifecycles_run_id"))
        batch_op.drop_index(batch_op.f("ix_setup_lifecycles_created_at"))
        batch_op.drop_index(batch_op.f("ix_setup_lifecycles_as_of"))

    op.drop_table("setup_lifecycles")
    # ### end Alembic commands ###
