"""watchlist performance

Revision ID: 0014
Revises: 0013
Create Date: 2026-06-21 00:28:13.269794
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watchlist_performance",
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("horizon", sa.String(length=16), nullable=False),
        sa.Column("horizon_label", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("conviction", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("expected_move_pct", sa.Float(), nullable=True),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("watchlist_entry_id", sa.Integer(), nullable=True),
        sa.Column("reference_price", sa.Float(), nullable=False),
        sa.Column("ret_1d", sa.Float(), nullable=True),
        sa.Column("ret_1w", sa.Float(), nullable=True),
        sa.Column("ret_1m", sa.Float(), nullable=True),
        sa.Column("mfe", sa.Float(), nullable=True),
        sa.Column("mae", sa.Float(), nullable=True),
        sa.Column("bars_tracked", sa.Integer(), nullable=False),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("last_price", sa.Float(), nullable=True),
        sa.Column("last_tracked_date", sa.Date(), nullable=True),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("config_hash", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watchlist_performance")),
        sa.UniqueConstraint("run_id", "as_of", "horizon", "symbol", name="uq_watchlist_perf_key"),
    )
    with op.batch_alter_table("watchlist_performance", schema=None) as batch_op:
        batch_op.create_index("ix_watchlist_perf_horizon_asof", ["horizon", "as_of"], unique=False)
        batch_op.create_index(batch_op.f("ix_watchlist_performance_as_of"), ["as_of"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_watchlist_performance_complete"), ["complete"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_watchlist_performance_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_watchlist_performance_horizon"), ["horizon"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_watchlist_performance_rank"), ["rank"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_watchlist_performance_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_watchlist_performance_symbol"), ["symbol"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_watchlist_performance_watchlist_entry_id"),
            ["watchlist_entry_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("watchlist_performance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watchlist_performance_watchlist_entry_id"))
        batch_op.drop_index(batch_op.f("ix_watchlist_performance_symbol"))
        batch_op.drop_index(batch_op.f("ix_watchlist_performance_run_id"))
        batch_op.drop_index(batch_op.f("ix_watchlist_performance_rank"))
        batch_op.drop_index(batch_op.f("ix_watchlist_performance_horizon"))
        batch_op.drop_index(batch_op.f("ix_watchlist_performance_created_at"))
        batch_op.drop_index(batch_op.f("ix_watchlist_performance_complete"))
        batch_op.drop_index(batch_op.f("ix_watchlist_performance_as_of"))
        batch_op.drop_index("ix_watchlist_perf_horizon_asof")

    op.drop_table("watchlist_performance")
    # ### end Alembic commands ###
