"""user universes

Revision ID: f826f6435ac5
Revises: 0014
Create Date: 2026-06-23 08:48:36.482473
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_universes",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("symbols", sa.JSON(), nullable=False),
        sa.Column("sectors", sa.JSON(), nullable=True),
        sa.Column("source", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_universes")),
        sa.UniqueConstraint("key", name="uq_user_universes_key"),
    )
    with op.batch_alter_table("user_universes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_universes_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_universes_key"), ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_universes_kind"), ["kind"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_universes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_universes_kind"))
        batch_op.drop_index(batch_op.f("ix_user_universes_key"))
        batch_op.drop_index(batch_op.f("ix_user_universes_created_at"))

    op.drop_table("user_universes")
    # ### end Alembic commands ###
