"""scan metadata

Revision ID: 889a488cfc57
Revises: 0015
Create Date: 2026-06-23 09:27:51.818766
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_metadata",
        sa.Column("scan_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("universe", sa.String(length=64), nullable=False),
        sa.Column("bar_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pull_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("symbol_count", sa.Integer(), nullable=False),
        sa.Column("data_age_minutes", sa.Float(), nullable=True),
        sa.Column("stale", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_metadata")),
        sa.UniqueConstraint("scan_id", name="uq_scan_metadata_scan_id"),
    )
    with op.batch_alter_table("scan_metadata", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scan_metadata_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_scan_metadata_scan_id"), ["scan_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_metadata_stale"), ["stale"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_metadata", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_metadata_stale"))
        batch_op.drop_index(batch_op.f("ix_scan_metadata_scan_id"))
        batch_op.drop_index(batch_op.f("ix_scan_metadata_created_at"))

    op.drop_table("scan_metadata")
    # ### end Alembic commands ###
