"""trade lifecycle

Revision ID: 0022
Revises: 0021
Create Date: 2026-07-01 20:06:24.119887
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0022"
down_revision: str | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracked_trades",
        sa.Column("trade_uid", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("recommended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("instrument", sa.String(length=16), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("stop_price", sa.Float(), nullable=False),
        sa.Column("targets", sa.JSON(), nullable=True),
        sa.Column("conviction_score", sa.Float(), nullable=True),
        sa.Column("conviction_band", sa.String(length=8), nullable=True),
        sa.Column("regime", sa.String(length=16), nullable=True),
        sa.Column("sector", sa.String(length=32), nullable=True),
        sa.Column("thesis", sa.Text(), nullable=True),
        sa.Column("entry_atr", sa.Float(), nullable=True),
        sa.Column("sector_rs", sa.Float(), nullable=True),
        sa.Column("momentum_score", sa.Float(), nullable=True),
        sa.Column("analog_expectancy_r", sa.Float(), nullable=True),
        sa.Column("current_thesis_strength", sa.Float(), nullable=True),
        sa.Column("trade_health", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("last_evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_reason", sa.String(length=160), nullable=True),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracked_trades")),
    )
    with op.batch_alter_table("tracked_trades", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tracked_trades_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tracked_trades_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tracked_trades_status"), ["status"], unique=False)
        batch_op.create_index("ix_tracked_trades_status_symbol", ["status", "symbol"], unique=False)
        batch_op.create_index(batch_op.f("ix_tracked_trades_symbol"), ["symbol"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tracked_trades_trade_health"), ["trade_health"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tracked_trades_trade_uid"), ["trade_uid"], unique=True)

    op.create_table(
        "trade_evaluations",
        sa.Column("trade_uid", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_conviction", sa.Float(), nullable=True),
        sa.Column("conviction_delta", sa.Float(), nullable=True),
        sa.Column("momentum_trend", sa.String(length=8), nullable=False),
        sa.Column("rs_trend", sa.String(length=8), nullable=False),
        sa.Column("volume_trend", sa.String(length=8), nullable=False),
        sa.Column("atr_expansion", sa.Float(), nullable=True),
        sa.Column("regime_at_entry", sa.String(length=16), nullable=True),
        sa.Column("regime_now", sa.String(length=16), nullable=True),
        sa.Column("regime_changed", sa.Boolean(), nullable=False),
        sa.Column("sector_delta", sa.Float(), nullable=True),
        sa.Column("analog_delta", sa.Float(), nullable=True),
        sa.Column("thesis_strength", sa.Float(), nullable=False),
        sa.Column("thesis_stability", sa.Float(), nullable=False),
        sa.Column("health", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("stop_breached", sa.Boolean(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_evaluations")),
    )
    with op.batch_alter_table("trade_evaluations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trade_evaluations_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_trade_evaluations_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_trade_evaluations_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trade_evaluations_symbol"), ["symbol"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_trade_evaluations_trade_uid"), ["trade_uid"], unique=False
        )
        batch_op.create_index(
            "ix_trade_evaluations_uid_at", ["trade_uid", "evaluated_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trade_evaluations", schema=None) as batch_op:
        batch_op.drop_index("ix_trade_evaluations_uid_at")
        batch_op.drop_index(batch_op.f("ix_trade_evaluations_trade_uid"))
        batch_op.drop_index(batch_op.f("ix_trade_evaluations_symbol"))
        batch_op.drop_index(batch_op.f("ix_trade_evaluations_run_id"))
        batch_op.drop_index(batch_op.f("ix_trade_evaluations_created_at"))
        batch_op.drop_index(batch_op.f("ix_trade_evaluations_action"))

    op.drop_table("trade_evaluations")
    with op.batch_alter_table("tracked_trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracked_trades_trade_uid"))
        batch_op.drop_index(batch_op.f("ix_tracked_trades_trade_health"))
        batch_op.drop_index(batch_op.f("ix_tracked_trades_symbol"))
        batch_op.drop_index("ix_tracked_trades_status_symbol")
        batch_op.drop_index(batch_op.f("ix_tracked_trades_status"))
        batch_op.drop_index(batch_op.f("ix_tracked_trades_run_id"))
        batch_op.drop_index(batch_op.f("ix_tracked_trades_created_at"))

    op.drop_table("tracked_trades")
    # ### end Alembic commands ###
