"""tracked trade realized outcome

Revision ID: 0023
Revises: 0022
Create Date: 2026-07-01 21:01:17.351226
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0023"
down_revision: str | None = "0022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracked_trades", schema=None) as batch_op:
        batch_op.add_column(sa.Column("journal_trade_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("realized_r", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("realized_pnl", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("realized_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_tracked_trades_journal_trade_id"), ["journal_trade_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_tracked_trades_journal_trade_id_trades"),
            "trades",
            ["journal_trade_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracked_trades", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_tracked_trades_journal_trade_id_trades"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_tracked_trades_journal_trade_id"))
        batch_op.drop_column("realized_at")
        batch_op.drop_column("realized_pnl")
        batch_op.drop_column("realized_r")
        batch_op.drop_column("journal_trade_id")

    # ### end Alembic commands ###
