"""trade health explainability

Revision ID: 0024
Revises: 0023
Create Date: 2026-07-01 21:20:42.402086
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0024"
down_revision: str | None = "0023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracked_trades", schema=None) as batch_op:
        batch_op.add_column(sa.Column("current_health_score", sa.Float(), nullable=True))

    with op.batch_alter_table("trade_evaluations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("health_score", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("health_breakdown", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("explanation", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trade_evaluations", schema=None) as batch_op:
        batch_op.drop_column("explanation")
        batch_op.drop_column("health_breakdown")
        batch_op.drop_column("health_score")

    with op.batch_alter_table("tracked_trades", schema=None) as batch_op:
        batch_op.drop_column("current_health_score")

    # ### end Alembic commands ###
