"""market pulse tables

Revision ID: 0025
Revises: 0024
Create Date: 2026-07-01 22:03:58.930829
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0025"
down_revision: str | None = "0024"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("symbol", sa.String(length=24), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("text", sa.String(length=300), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_activities_category"), ["category"], unique=False)
        batch_op.create_index(batch_op.f("ix_activities_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_activities_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_activities_symbol"), ["symbol"], unique=False)
        batch_op.create_index(batch_op.f("ix_activities_ts"), ["ts"], unique=False)

    op.create_table(
        "alerts",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("symbol", sa.String(length=24), nullable=True),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=400), nullable=False),
        sa.Column("dedupe_key", sa.String(length=160), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_alerts_dedupe_key")),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_alerts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_severity"), ["severity"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_symbol"), ["symbol"], unique=False)
        batch_op.create_index(batch_op.f("ix_alerts_ts"), ["ts"], unique=False)

    op.create_table(
        "scan_deltas",
        sa.Column("scan_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("prev_scan_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("symbol", sa.String(length=24), nullable=True),
        sa.Column("metric", sa.String(length=32), nullable=False),
        sa.Column("previous_value", sa.Float(), nullable=True),
        sa.Column("new_value", sa.Float(), nullable=True),
        sa.Column("previous_text", sa.String(length=64), nullable=True),
        sa.Column("new_text", sa.String(length=64), nullable=True),
        sa.Column("delta", sa.Float(), nullable=True),
        sa.Column("direction", sa.String(length=12), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_deltas")),
    )
    with op.batch_alter_table("scan_deltas", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scan_deltas_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_deltas_direction"), ["direction"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_deltas_metric"), ["metric"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_deltas_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_deltas_scan_ts"), ["scan_ts"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_deltas_symbol"), ["symbol"], unique=False)
        batch_op.create_index(
            "ix_scan_deltas_symbol_metric", ["symbol", "metric", "scan_ts"], unique=False
        )

    op.create_table(
        "scan_snapshots",
        sa.Column("scan_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("market_state", sa.String(length=16), nullable=True),
        sa.Column("candidates", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_snapshots")),
    )
    with op.batch_alter_table("scan_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scan_snapshots_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_scan_snapshots_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_snapshots_scan_ts"), ["scan_ts"], unique=False)

    op.create_table(
        "scan_stats",
        sa.Column("scan_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("symbols_processed", sa.Integer(), nullable=False),
        sa.Column("symbols_failed", sa.Integer(), nullable=False),
        sa.Column("provider_latency_ms", sa.Float(), nullable=True),
        sa.Column("db_writes", sa.Integer(), nullable=False),
        sa.Column("convictions_generated", sa.Integer(), nullable=False),
        sa.Column("watchlists_generated", sa.Integer(), nullable=False),
        sa.Column("alerts_generated", sa.Integer(), nullable=False),
        sa.Column("deltas_generated", sa.Integer(), nullable=False),
        sa.Column("activities_generated", sa.Integer(), nullable=False),
        sa.Column("symbols_skipped", sa.Integer(), nullable=True),
        sa.Column("symbols_recomputed", sa.Integer(), nullable=True),
        sa.Column("cache_hit_rate", sa.Float(), nullable=True),
        sa.Column("memory_mb", sa.Float(), nullable=True),
        sa.Column("cpu_percent", sa.Float(), nullable=True),
        sa.Column("degraded", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_stats")),
    )
    with op.batch_alter_table("scan_stats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scan_stats_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_stats_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scan_stats_scan_ts"), ["scan_ts"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scan_stats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_stats_scan_ts"))
        batch_op.drop_index(batch_op.f("ix_scan_stats_run_id"))
        batch_op.drop_index(batch_op.f("ix_scan_stats_created_at"))

    op.drop_table("scan_stats")
    with op.batch_alter_table("scan_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_snapshots_scan_ts"))
        batch_op.drop_index(batch_op.f("ix_scan_snapshots_run_id"))
        batch_op.drop_index(batch_op.f("ix_scan_snapshots_created_at"))

    op.drop_table("scan_snapshots")
    with op.batch_alter_table("scan_deltas", schema=None) as batch_op:
        batch_op.drop_index("ix_scan_deltas_symbol_metric")
        batch_op.drop_index(batch_op.f("ix_scan_deltas_symbol"))
        batch_op.drop_index(batch_op.f("ix_scan_deltas_scan_ts"))
        batch_op.drop_index(batch_op.f("ix_scan_deltas_run_id"))
        batch_op.drop_index(batch_op.f("ix_scan_deltas_metric"))
        batch_op.drop_index(batch_op.f("ix_scan_deltas_direction"))
        batch_op.drop_index(batch_op.f("ix_scan_deltas_created_at"))

    op.drop_table("scan_deltas")
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_ts"))
        batch_op.drop_index(batch_op.f("ix_alerts_symbol"))
        batch_op.drop_index(batch_op.f("ix_alerts_severity"))
        batch_op.drop_index(batch_op.f("ix_alerts_run_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_kind"))
        batch_op.drop_index(batch_op.f("ix_alerts_created_at"))

    op.drop_table("alerts")
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activities_ts"))
        batch_op.drop_index(batch_op.f("ix_activities_symbol"))
        batch_op.drop_index(batch_op.f("ix_activities_run_id"))
        batch_op.drop_index(batch_op.f("ix_activities_created_at"))
        batch_op.drop_index(batch_op.f("ix_activities_category"))

    op.drop_table("activities")
    # ### end Alembic commands ###
