"""brokerage simulation tables

Revision ID: 0027
Revises: 0026
Create Date: 2026-07-03 01:24:22.769352
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0027"
down_revision: str | None = "0026"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "broker_account_history",
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("cash", sa.Float(), nullable=False),
        sa.Column("settled_cash", sa.Float(), nullable=False),
        sa.Column("unsettled_cash", sa.Float(), nullable=False),
        sa.Column("equity", sa.Float(), nullable=False),
        sa.Column("portfolio_value", sa.Float(), nullable=False),
        sa.Column("buying_power", sa.Float(), nullable=False),
        sa.Column("open_risk", sa.Float(), nullable=False),
        sa.Column("daily_pnl", sa.Float(), nullable=False),
        sa.Column("total_pnl", sa.Float(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_account_history")),
    )
    with op.batch_alter_table("broker_account_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_broker_account_history_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_broker_account_history_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_broker_account_history_ts"), ["ts"], unique=False)
        batch_op.create_index("ix_broker_history_account_ts", ["account_id", "ts"], unique=False)

    op.create_table(
        "broker_accounts",
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("starting_cash", sa.Float(), nullable=False),
        sa.Column("cash", sa.Float(), nullable=False),
        sa.Column("margin_multiplier", sa.Float(), nullable=False),
        sa.Column("settlement_days", sa.Integer(), nullable=False),
        sa.Column("day_start_equity", sa.Float(), nullable=True),
        sa.Column("day_start_date", sa.String(length=10), nullable=True),
        sa.Column("pending_settlements", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_accounts")),
        sa.UniqueConstraint("account_id", name=op.f("uq_broker_accounts_account_id")),
    )
    with op.batch_alter_table("broker_accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_broker_accounts_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "broker_fills",
        sa.Column("order_id", sa.String(length=96), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("fees", sa.Float(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("partial", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=400), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_fills")),
    )
    with op.batch_alter_table("broker_fills", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_broker_fills_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_broker_fills_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_broker_fills_order_id"), ["order_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_broker_fills_symbol"), ["symbol"], unique=False)
        batch_op.create_index(batch_op.f("ix_broker_fills_ts"), ["ts"], unique=False)

    op.create_table(
        "broker_order_events",
        sa.Column("order_id", sa.String(length=96), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=False),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=400), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_order_events")),
    )
    with op.batch_alter_table("broker_order_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_broker_order_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_broker_order_events_order_id"), ["order_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_broker_order_events_ts"), ["ts"], unique=False)

    op.create_table(
        "broker_orders",
        sa.Column("order_id", sa.String(length=96), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("time_in_force", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("limit_price", sa.Float(), nullable=True),
        sa.Column("stop_price", sa.Float(), nullable=True),
        sa.Column("trail_percent", sa.Float(), nullable=True),
        sa.Column("trail_amount", sa.Float(), nullable=True),
        sa.Column("trail_extreme", sa.Float(), nullable=True),
        sa.Column("filled_quantity", sa.Integer(), nullable=False),
        sa.Column("avg_fill_price", sa.Float(), nullable=True),
        sa.Column("total_fees", sa.Float(), nullable=False),
        sa.Column("reject_reason", sa.String(length=255), nullable=True),
        sa.Column("parent_order_id", sa.String(length=96), nullable=True),
        sa.Column("oco_group", sa.String(length=96), nullable=True),
        sa.Column("link_role", sa.String(length=16), nullable=True),
        sa.Column("instrument", sa.String(length=24), nullable=False),
        sa.Column("multiplier", sa.Integer(), nullable=False),
        sa.Column("note", sa.String(length=400), nullable=True),
        sa.Column("created_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_orders")),
        sa.UniqueConstraint("order_id", name=op.f("uq_broker_orders_order_id")),
    )
    with op.batch_alter_table("broker_orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_broker_orders_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            "ix_broker_orders_account_status", ["account_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_broker_orders_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_broker_orders_created_ts"), ["created_ts"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_broker_orders_oco_group"), ["oco_group"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_broker_orders_parent_order_id"), ["parent_order_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_broker_orders_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_broker_orders_symbol"), ["symbol"], unique=False)

    op.create_table(
        "broker_positions",
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("instrument", sa.String(length=24), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("max_quantity", sa.Integer(), nullable=False),
        sa.Column("multiplier", sa.Integer(), nullable=False),
        sa.Column("avg_cost", sa.Float(), nullable=False),
        sa.Column("realized_pnl", sa.Float(), nullable=False),
        sa.Column("total_fees", sa.Float(), nullable=False),
        sa.Column("last_price", sa.Float(), nullable=True),
        sa.Column("last_mark_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column("day_start_price", sa.Float(), nullable=True),
        sa.Column("mfe_price", sa.Float(), nullable=True),
        sa.Column("mae_price", sa.Float(), nullable=True),
        sa.Column("stop_price", sa.Float(), nullable=True),
        sa.Column("initial_risk_per_unit", sa.Float(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_positions")),
    )
    with op.batch_alter_table("broker_positions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_broker_positions_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            "ix_broker_positions_account_open", ["account_id", "is_open"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_broker_positions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_broker_positions_is_open"), ["is_open"], unique=False)
        batch_op.create_index(batch_op.f("ix_broker_positions_symbol"), ["symbol"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("broker_positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_broker_positions_symbol"))
        batch_op.drop_index(batch_op.f("ix_broker_positions_is_open"))
        batch_op.drop_index(batch_op.f("ix_broker_positions_created_at"))
        batch_op.drop_index("ix_broker_positions_account_open")
        batch_op.drop_index(batch_op.f("ix_broker_positions_account_id"))

    op.drop_table("broker_positions")
    with op.batch_alter_table("broker_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_broker_orders_symbol"))
        batch_op.drop_index(batch_op.f("ix_broker_orders_status"))
        batch_op.drop_index(batch_op.f("ix_broker_orders_parent_order_id"))
        batch_op.drop_index(batch_op.f("ix_broker_orders_oco_group"))
        batch_op.drop_index(batch_op.f("ix_broker_orders_created_ts"))
        batch_op.drop_index(batch_op.f("ix_broker_orders_created_at"))
        batch_op.drop_index("ix_broker_orders_account_status")
        batch_op.drop_index(batch_op.f("ix_broker_orders_account_id"))

    op.drop_table("broker_orders")
    with op.batch_alter_table("broker_order_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_broker_order_events_ts"))
        batch_op.drop_index(batch_op.f("ix_broker_order_events_order_id"))
        batch_op.drop_index(batch_op.f("ix_broker_order_events_created_at"))

    op.drop_table("broker_order_events")
    with op.batch_alter_table("broker_fills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_broker_fills_ts"))
        batch_op.drop_index(batch_op.f("ix_broker_fills_symbol"))
        batch_op.drop_index(batch_op.f("ix_broker_fills_order_id"))
        batch_op.drop_index(batch_op.f("ix_broker_fills_created_at"))
        batch_op.drop_index(batch_op.f("ix_broker_fills_account_id"))

    op.drop_table("broker_fills")
    with op.batch_alter_table("broker_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_broker_accounts_created_at"))

    op.drop_table("broker_accounts")
    with op.batch_alter_table("broker_account_history", schema=None) as batch_op:
        batch_op.drop_index("ix_broker_history_account_ts")
        batch_op.drop_index(batch_op.f("ix_broker_account_history_ts"))
        batch_op.drop_index(batch_op.f("ix_broker_account_history_created_at"))
        batch_op.drop_index(batch_op.f("ix_broker_account_history_account_id"))

    op.drop_table("broker_account_history")
    # ### end Alembic commands ###
