"""committee meetings table

Revision ID: 0028
Revises: 0027
Create Date: 2026-07-03 02:08:52.069591
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0028"
down_revision: str | None = "0027"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "committee_meetings",
        sa.Column("meeting_uid", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("context", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=8), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("agreement", sa.Float(), nullable=False),
        sa.Column("votes", sa.JSON(), nullable=False),
        sa.Column("consensus", sa.String(length=2000), nullable=False),
        sa.Column("dissent", sa.String(length=2000), nullable=False),
        sa.Column("narrative", sa.String(length=3000), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_committee_meetings")),
        sa.UniqueConstraint("meeting_uid", name=op.f("uq_committee_meetings_meeting_uid")),
    )
    with op.batch_alter_table("committee_meetings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_committee_meetings_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_committee_meetings_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_committee_meetings_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_committee_meetings_symbol"), ["symbol"], unique=False)
        batch_op.create_index(batch_op.f("ix_committee_meetings_ts"), ["ts"], unique=False)
        batch_op.create_index("ix_committee_symbol_ts", ["symbol", "ts"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("committee_meetings", schema=None) as batch_op:
        batch_op.drop_index("ix_committee_symbol_ts")
        batch_op.drop_index(batch_op.f("ix_committee_meetings_ts"))
        batch_op.drop_index(batch_op.f("ix_committee_meetings_symbol"))
        batch_op.drop_index(batch_op.f("ix_committee_meetings_run_id"))
        batch_op.drop_index(batch_op.f("ix_committee_meetings_created_at"))
        batch_op.drop_index(batch_op.f("ix_committee_meetings_action"))

    op.drop_table("committee_meetings")
    # ### end Alembic commands ###
