"""shadow trades table

Revision ID: ce2b431deca0
Revises: 0028
Create Date: 2026-07-03 08:57:39.317402
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0029"
down_revision: str | None = "0028"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shadow_trades",
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("entered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("conviction_score", sa.Float(), nullable=True),
        sa.Column("expected_entry", sa.Float(), nullable=False),
        sa.Column("reference_entry", sa.Float(), nullable=False),
        sa.Column("entry_slippage_bps", sa.Float(), nullable=False),
        sa.Column("stop_price", sa.Float(), nullable=False),
        sa.Column("current_stop", sa.Float(), nullable=True),
        sa.Column("target_price", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_run_id", sa.String(length=64), nullable=True),
        sa.Column("expected_exit", sa.Float(), nullable=True),
        sa.Column("reference_exit", sa.Float(), nullable=True),
        sa.Column("exit_slippage_bps", sa.Float(), nullable=True),
        sa.Column("exit_reason", sa.String(length=32), nullable=True),
        sa.Column("expected_pnl", sa.Float(), nullable=True),
        sa.Column("expected_r", sa.Float(), nullable=True),
        sa.Column("mfe_price", sa.Float(), nullable=True),
        sa.Column("mae_price", sa.Float(), nullable=True),
        sa.Column("last_price", sa.Float(), nullable=True),
        sa.Column("last_eval_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evaluations", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shadow_trades")),
        sa.UniqueConstraint("run_id", "symbol", name="uq_shadow_trades_run_symbol"),
    )
    with op.batch_alter_table("shadow_trades", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shadow_trades_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_shadow_trades_entered_at"), ["entered_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_shadow_trades_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_shadow_trades_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_shadow_trades_symbol"), ["symbol"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shadow_trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shadow_trades_symbol"))
        batch_op.drop_index(batch_op.f("ix_shadow_trades_status"))
        batch_op.drop_index(batch_op.f("ix_shadow_trades_run_id"))
        batch_op.drop_index(batch_op.f("ix_shadow_trades_entered_at"))
        batch_op.drop_index(batch_op.f("ix_shadow_trades_created_at"))

    op.drop_table("shadow_trades")
    # ### end Alembic commands ###
