"""tracked trade management mode

Revision ID: 54ff4666f856
Revises: 0029
Create Date: 2026-07-03 22:36:37.008953
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0030"
down_revision: str | None = "0029"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracked_trades", schema=None) as batch_op:
        batch_op.add_column(sa.Column("management_mode", sa.String(length=8), nullable=False))
        batch_op.create_index(
            batch_op.f("ix_tracked_trades_management_mode"), ["management_mode"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tracked_trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracked_trades_management_mode"))
        batch_op.drop_column("management_mode")

    # ### end Alembic commands ###
